const getters = {
  sidebar: state => state.app.sidebar,
  device: state => state.app.device,
  token: state => state.user.token,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  roles: state => state.user.roles,
  user: state => state.user.user,
  company: state => state.user.user.userAllocation,
  loadMenus: state => state.user.loadMenus,
  permission_routers: state => state.permission.routers,
  addRouters: state => state.permission.addRouters,
  socketApi: state => state.api.socketApi,
  imagesUploadApi: state => state.api.imagesUploadApi,
  jeExcelUploadApi: state => state.api.jeExcelUploadApi,
  sysFileUploadApi: state => state.api.sysFileUploadApi,
  updateAvatarApi: state => state.api.updateAvatarApi,
  qiNiuUploadApi: state => state.api.qiNiuUploadApi,
  sqlApi: state => state.api.sqlApi,
  swaggerApi: state => state.api.swaggerApi,
  bsIncomeReport: state => state.api.bsIncomeReport,
  financialIncomeReport: state => state.api.financialIncomeReport,
  oneOffIncome: state => state.api.oneOffIncome,
  privateKanbans: state => state.kanban.privateKanbans,
  treeBody: state => state.tree.treeBody,
  treeConfig: state => state.tree.treeBody.config,
  highlightSid: state => state.tree.highlightSid,
  highlightSidCount: state => state.tree.highlightSidCount,
  selectedTreeDs: state => state.tree.treeBody.config.dsGroup.find(element => element.checked),
  jsPlumbConfig: state => state.tree.jsPlumbConfig,
  jsPlumb: state => state.tree.jsPlumb,
  jsPlumbInstance: state => state.tree.jsPlumbInstance
}
export default getters
